from __future__ import annotations

import json
import subprocess
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from .config import AppConfig
from .douyin_web import DOUYIN_VIEWPORT, _launch_context, _load_playwright


def teach_douyin_ai(
    config: AppConfig,
    *,
    url: str = "https://www.douyin.com/",
    wait_seconds: int = 240,
    output: Path | None = None,
) -> str:
    output_path = output or (config.root / ".state" / "douyin_ai_teach_profile.json")
    debug_dir = config.root / ".state" / "debug"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    debug_dir.mkdir(parents=True, exist_ok=True)

    sync_playwright = _load_playwright()
    collected: list[dict[str, Any]] = []
    frame_event_offsets: dict[str, int] = {}
    final_snapshot: dict[str, Any] = {}
    clipboard_text = ""
    clipboard_samples: list[dict[str, Any]] = []
    screenshot_path = debug_dir / "douyin_ai_teach_final.png"

    with sync_playwright() as playwright:
        context = _launch_context(playwright, config, headless=False)
        page = context.pages[0] if context.pages else context.new_page()
        try:
            page.set_viewport_size(dict(DOUYIN_VIEWPORT))
        except Exception:
            pass
        page.goto(url, wait_until="domcontentloaded", timeout=60000)
        print("teach_mode=started", flush=True)
        print(f"operate_manually_seconds={wait_seconds}", flush=True)
        print("manual_steps=open video -> 问AI -> 输入问题 -> 等生成 -> 拉到底 -> 点复制", flush=True)

        started = time.time()
        while time.time() - started < wait_seconds:
            try:
                if page.is_closed():
                    break
                _inject_teach_recorder(page)
                collected.extend(_collect_teach_events(page, frame_event_offsets))
                sampled = _read_clipboard_text(page)
                if sampled and sampled != clipboard_text:
                    clipboard_text = sampled
                    clipboard_samples.append(
                        {
                            "at": datetime.now().isoformat(timespec="seconds"),
                            "length": len(sampled),
                            "head": sampled[:500],
                        }
                    )
                page.wait_for_timeout(1000)
            except Exception:
                break

        try:
            if not page.is_closed():
                _inject_teach_recorder(page)
                collected.extend(_collect_teach_events(page, frame_event_offsets))
                final_snapshot = _page_teach_snapshot(page)
                sampled = _read_clipboard_text(page)
                if sampled and sampled != clipboard_text:
                    clipboard_text = sampled
                    clipboard_samples.append(
                        {
                            "at": datetime.now().isoformat(timespec="seconds"),
                            "length": len(sampled),
                            "head": sampled[:500],
                        }
                    )
                try:
                    page.screenshot(path=str(screenshot_path), full_page=False)
                except Exception:
                    pass
        except Exception:
            pass
        try:
            context.close()
        except Exception:
            pass

    profile = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "start_url": url,
        "wait_seconds": wait_seconds,
        "event_count": len(collected),
        "events": collected,
        "final_snapshot": final_snapshot,
        "clipboard_len": len(clipboard_text),
        "clipboard_text": clipboard_text,
        "clipboard_samples": clipboard_samples,
        "screenshot": str(screenshot_path),
        "notes": [
            "This profile is generated by manually operating Douyin AI once.",
            "Prefer iframe events whose frame_url contains search_ai_mobile.",
            "Do not use main-page send/danmaku controls as AI submit controls.",
        ],
    }
    output_path.write_text(json.dumps(profile, ensure_ascii=False, indent=2), encoding="utf-8")
    return f"teach_profile={output_path} events={len(collected)} clipboard_len={len(clipboard_text)} screenshot={screenshot_path}"


def _inject_teach_recorder(page: Any) -> None:
    script = r"""
() => {
  if (window.__douyinKbTeachInstalled) return true;
  window.__douyinKbTeachInstalled = true;
  window.__douyinKbTeachEvents = [];
  window.__douyinKbTeachSeq = 0;
  const normText = (value) => String(value || '').replace(/\s+/g, ' ').trim().slice(0, 240);
  const cssPath = (node) => {
    if (!node || node.nodeType !== 1) return '';
    const parts = [];
    let current = node;
    for (let depth = 0; current && current.nodeType === 1 && depth < 6; depth += 1, current = current.parentElement) {
      let part = current.tagName.toLowerCase();
      const id = current.getAttribute('id');
      if (id) {
        part += `#${CSS.escape(id)}`;
        parts.unshift(part);
        break;
      }
      const cls = (current.getAttribute('class') || '').split(/\s+/).filter(Boolean).slice(0, 2);
      if (cls.length) part += '.' + cls.map((item) => CSS.escape(item)).join('.');
      const parent = current.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children).filter((item) => item.tagName === current.tagName);
        if (siblings.length > 1) part += `:nth-of-type(${siblings.indexOf(current) + 1})`;
      }
      parts.unshift(part);
    }
    return parts.join(' > ');
  };
  const describe = (node) => {
    if (!node || node.nodeType !== 1) return {};
    const rect = node.getBoundingClientRect();
    return {
      tag: node.tagName,
      selector: cssPath(node),
      text: normText(node.innerText || node.textContent || node.value || ''),
      role: node.getAttribute('role') || '',
      aria_label: node.getAttribute('aria-label') || '',
      title: node.getAttribute('title') || '',
      placeholder: node.getAttribute('placeholder') || '',
      contenteditable: node.getAttribute('contenteditable') || '',
      class: node.getAttribute('class') || '',
      x: Math.round(rect.x),
      y: Math.round(rect.y),
      width: Math.round(rect.width),
      height: Math.round(rect.height),
    };
  };
  const push = (type, event, extra = {}) => {
    const target = event?.target?.closest?.('button,[role="button"],a,input,textarea,[contenteditable="true"],[role="textbox"],div,span') || event?.target;
    window.__douyinKbTeachEvents.push({
      seq: ++window.__douyinKbTeachSeq,
      type,
      at: Date.now(),
      frame_url: location.href,
      inner_width: window.innerWidth,
      inner_height: window.innerHeight,
      target: describe(target),
      active: describe(document.activeElement),
      extra,
    });
  };
  document.addEventListener('click', (event) => push('click', event, { button: event.button, client_x: Math.round(event.clientX), client_y: Math.round(event.clientY) }), true);
  document.addEventListener('input', (event) => push('input', event, { value: normText(event.target?.value || event.target?.innerText || event.target?.textContent || '') }), true);
  document.addEventListener('keydown', (event) => {
    if (event.key === 'Enter' || event.key === 'Tab' || event.key.toLowerCase() === 'v') {
      push('keydown', event, { key: event.key, ctrl: event.ctrlKey, meta: event.metaKey });
    }
  }, true);
  document.addEventListener('scroll', (event) => {
    const node = event.target === document ? document.scrollingElement : event.target;
    push('scroll', { target: node }, { scroll_top: Math.round(node?.scrollTop || 0), scroll_left: Math.round(node?.scrollLeft || 0) });
  }, true);
  return true;
}
"""
    for frame in list(page.frames):
        try:
            frame.evaluate(script)
        except Exception:
            continue


def _collect_teach_events(page: Any, offsets: dict[str, int]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for index, frame in enumerate(list(page.frames)):
        frame_key = f"{index}:{frame.url}"
        try:
            events = frame.evaluate("() => window.__douyinKbTeachEvents || []")
        except Exception:
            continue
        offset = offsets.get(frame_key, 0)
        new_events = events[offset:]
        offsets[frame_key] = len(events)
        for item in new_events:
            item["frame_index"] = index
            out.append(item)
    return out


def _page_teach_snapshot(page: Any) -> dict[str, Any]:
    frames: list[dict[str, Any]] = []
    for index, frame in enumerate(list(page.frames)):
        try:
            body = frame.locator("body").inner_text(timeout=1000)
        except Exception:
            body = ""
        try:
            candidates = frame.evaluate(
                r"""
() => Array.from(document.querySelectorAll('textarea,input,[contenteditable="true"],[role="textbox"],button,[role="button"],a,div,span'))
  .map((node) => {
    const rect = node.getBoundingClientRect();
    const style = window.getComputedStyle(node);
    const text = String(node.innerText || node.textContent || node.value || '').replace(/\s+/g, ' ').trim();
    return {
      tag: node.tagName,
      text: text.slice(0, 160),
      role: node.getAttribute('role') || '',
      aria_label: node.getAttribute('aria-label') || '',
      title: node.getAttribute('title') || '',
      placeholder: node.getAttribute('placeholder') || '',
      contenteditable: node.getAttribute('contenteditable') || '',
      class: node.getAttribute('class') || '',
      x: Math.round(rect.x),
      y: Math.round(rect.y),
      width: Math.round(rect.width),
      height: Math.round(rect.height),
      visible: rect.width > 4 && rect.height > 4 && style.display !== 'none' && style.visibility !== 'hidden'
    };
  })
  .filter((item) => item.visible && (
    item.contenteditable === 'true' ||
    item.role === 'textbox' ||
    item.placeholder ||
    item.text.includes('复制') ||
    item.text.includes('发送') ||
    item.text.includes('问AI') ||
    item.text.toLowerCase().includes('copy')
  ))
  .slice(0, 120)
"""
            )
        except Exception:
            candidates = []
        frames.append(
            {
                "index": index,
                "url": frame.url,
                "body_head": body[:1200],
                "candidates": candidates,
            }
        )
    return {"url": page.url, "frames": frames}


def _read_clipboard_text(page: Any) -> str:
    try:
        page.context.grant_permissions(["clipboard-read", "clipboard-write"], origin="https://www.douyin.com")
    except Exception:
        pass
    try:
        text = str(page.evaluate("navigator.clipboard.readText()") or "")
        if text:
            return text
    except Exception:
        pass
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", "Get-Clipboard -Raw"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="ignore",
            timeout=3,
        )
        if result.returncode == 0:
            return result.stdout or ""
    except Exception:
        pass
    return ""
